name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        cfg:
        - { os: ubuntu-18.04, cxx: g++-10, python: 3.9 }
        - { os: ubuntu-18.04, cxx: g++-8, python: 3.9 }
        - { os: ubuntu-18.04, cxx: g++-10, python: 3.6 }
        - { os: ubuntu-18.04, cxx: g++-8, python: 3.6 }
        - { os: ubuntu-18.04, cxx: clang++-9, python: 3.9 }
        - { os: macos-latest, cxx: clang++, python: 3.9 }
        - { os: macos-latest, cxx: g++-9, python: 3.9 }

    runs-on: ${{ matrix.cfg.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.cfg.python }}
    - name: pip
      run: python3 -m pip install pybind11 setuptools wheel
    - name: make
      run: CXX=${{ matrix.cfg.cxx }} make -j8
    - name: sdist
      run: python3 setup.py sdist
    - name: install
      run: CXX=${{ matrix.cfg.cxx }} python3 -m pip install dist/*.tar.gz
    - name: test
      run: cd ../ && python3 -c 'import ffcache'
    - uses: actions/upload-artifact@v2
      with:
        name: ffcache
        path: |
          dist/*
