name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: sudo apt-get update &&
           sudo apt-get install -y g++ python3.8-dev make python3-pip
    - name: install pybind11
      run: pip3 install pybind11
    - name: make
      run: make
    - uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: |
          ffcache-*
          *.so
  test:
    runs-on: ubuntu-18.04
    needs: build

    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@master
      with:
        name: my-artifact
        path: |
          *.so
          ffcache-*
    - name: test
      run: make test
    